//
//  GeneralViewController.swift
//  RateBike
//
//  Created by Сергей Вихляев on 04.05.2020.
//  Copyright (c) 2020 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GeneralDisplayLogic: class {
    func displaySomething()
}

class GeneralViewController: UIViewController {
    var presenter: GeneralViewControllerOutput!
    
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
    }
    
    // MARK: Action
    
    func someAction() {
        presenter.someActionTriggered()
    }
}

// MARK: Setup
extension GeneralViewController {
    private func setup() {
    }
}

extension GeneralViewController: GeneralDisplayLogic {
    func displaySomething() {
    }
}
