//
//  GeneralInteractor.swift
//  RateBike
//
//  Created by Сергей Вихляев on 04.05.2020.
//  Copyright (c) 2020 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GeneralBusinessLogic {
}

protocol GeneralDataStore {
    var name: String { get set }
}

class GeneralInteractor: NSObject, GeneralDataStore {
    weak var presenter: GeneralPresentationLogic!
    var worker: CoreDataWorker?
    var name: String = ""
    
    // MARK: Do something
}

extension GeneralInteractor: GeneralBusinessLogic {
    
}

extension GeneralInteractor: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        return UITableViewCell()
    }
    
    
}
