//
//  GeneralPresenter.swift
//  RateBike
//
//  Created by Сергей Вихляев on 04.05.2020.
//  Copyright (c) 2020 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GeneralPresentationLogic: class {
    func needToInsertRows(count: Int, dataUpdatesBlock: ()->())
}

protocol GeneralViewControllerOutput {
    func viewIsReady()
}

class GeneralPresenter: NSObject, GeneralPresentationLogic {
    
    var interactor: GeneralBusinessLogic!
    weak var viewController: GeneralDisplayLogic!
    var router: GeneralRoutingLogic!
    
    weak var tableView: UITableView!
    
    // MARK: Presentation Logic
    func needToInsertRows(count: Int, dataUpdatesBlock: () -> ()) {
        
        dataUpdatesBlock()
        tableView.reloadData()
        /*
        // counting
        var indexPaths = [IndexPath]()
        (0..<count).forEach { (row) in
            indexPaths.append(IndexPath(row: row, section: 0))
        }
        
        // updates
        tableView.beginUpdates()
        dataUpdatesBlock()
        tableView.insertRows(at: indexPaths, with: .automatic)
        tableView.endUpdates()*/
    }
}

extension GeneralPresenter: GeneralViewControllerOutput {
    func viewIsReady() {
        interactor?.setupFirstData()
    }
}

extension GeneralPresenter: UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 60
    }
}
