//
//  GeneralConfigurator.swift
//  RateBike
//
//  Created by Сергей Вихляев on 04.05.2020.
//  Copyright (c) 2020 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class GeneralConfigurator: BaseConfiguratorProtocol {
    func configure(viewController: UIViewController, navigationController: UINavigationController?) {
        let viewController = viewController as! GeneralViewController
        
        let presenter = GeneralPresenter()
        let interactor = GeneralInteractor()
        let router = GeneralRouter(withNavigationController: navigationController)
        
        interactor.presenter = presenter
        viewController.presenter = presenter
        presenter.viewController = viewController
        presenter.interactor = interactor
        presenter.router = router
        
        viewController.loadView()
        viewController.viewDidLoad()
        
        presenter.tableView = viewController.tableView
        viewController.tableView.dataSource = interactor
        viewController.tableView.delegate = presenter
        
        presenter.viewIsReady()
    }
    
    class func rootViewController() -> UIViewController {
        let navigationController = UINavigationController()
        let generalViewController = GeneralViewController()
        GeneralConfigurator().configure(viewController: generalViewController, navigationController: navigationController)
        navigationController.viewControllers = [generalViewController]
        return navigationController
    }
}
