//
//  GeneralWorker.swift
//  RateBike
//
//  Created by Сергей Вихляев on 04.05.2020.
//  Copyright (c) 2020 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

class CoreDataWorker {
    func doSomeWork() {
    }
}
